"""Markdown report, log, and summary generation."""

from __future__ import annotations

from collections import OrderedDict
from datetime import datetime
from pathlib import Path
from typing import Optional

from opencode_agent.core.models import ScanTask


def generate_report(task: ScanTask) -> str:
    """生成 Markdown 审查报告 — 只展示审查结果（nga stdout）"""
    lines = []

    if task.function_name:
        lines.append(f"# 代码审查报告 - {task.function_name}")
        lines.append("")
        lines.append(f"**文件**: `{task.file_path}`")
        lines.append(f"**函数**: `{task.function_name}`")
    else:
        lines.append(f"# 代码审查报告 - {Path(task.file_path).name}")
        lines.append("")
        lines.append(f"**文件**: `{task.file_path}`")

    lines.append(f"**任务ID**: `{task.task_id}`")
    lines.append(f"**扫描时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**耗时**: {task.duration}s")
    lines.append(f"**状态**: {'完成' if task.status == 'done' else '失败'}")
    lines.append("")
    lines.append("---")
    lines.append("")

    if task.stdout.strip():
        # 直接展示 nga 的审查结果，不加代码块包装
        lines.append(task.stdout)
    else:
        lines.append("*无审查结果*")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by OpenCode Orchestrator*")

    return "\n".join(lines)


def generate_log(task: ScanTask) -> str:
    """生成运行日志 — 保存运行详情和 stderr"""
    lines = []
    lines.append(f"=== Task: {task.task_id} ===")
    lines.append(f"File: {task.file_path}")
    lines.append(f"Status: {task.status}")
    lines.append(f"Duration: {task.duration}s")
    lines.append(f"Return code: {task.returncode}")
    lines.append(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    if task.error:
        lines.append("=== Error ===")
        lines.append(task.error)
        lines.append("")

    lines.append("=== STDERR ===")
    if task.stderr.strip():
        lines.append(task.stderr)
    else:
        lines.append("*No stderr output*")

    return "\n".join(lines)


def generate_summary(tasks: list[ScanTask], total_time: float, output_dir: Path) -> str:
    """生成 Markdown 汇总报告"""
    done = sum(1 for t in tasks if t.status == "done")
    failed = sum(1 for t in tasks if t.status == "failed")

    lines = []
    lines.append("# 扫描汇总报告")
    lines.append("")
    lines.append("## 统计")
    lines.append("")
    lines.append("| 项目 | 值 |")
    lines.append("|------|-----|")
    lines.append(f"| 总任务数 | {len(tasks)} |")
    lines.append(f"| 成功 | {done} |")
    lines.append(f"| 失败 | {failed} |")
    lines.append(f"| 总耗时 | {total_time:.1f}s |")
    lines.append(f"| 生成时间 | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |")
    lines.append("")

    lines.append("## 详细结果")
    lines.append("")

    # 按文件分组
    file_groups: OrderedDict[str, list[ScanTask]] = OrderedDict()
    for t in tasks:
        file_groups.setdefault(t.file_path, []).append(t)

    for file_path, file_tasks in file_groups.items():
        lines.append(f"### `{file_path}`")
        lines.append("")
        lines.append("| # | 函数 | 状态 | 耗时 | 报告 | 日志 |")
        lines.append("|---|------|------|------|------|------|")

        for i, t in enumerate(file_tasks, 1):
            status_icon = "✅" if t.status == "done" else "❌"
            func_name = t.function_name or "(整文件)"
            report_name = Path(t.report_file).name
            log_name = Path(t.log_file).name
            # 链接相对于 summary.md 所在目录
            report_link = f"[{report_name}]({Path(t.report_file).relative_to(output_dir)})"
            log_link = f"[{log_name}]({Path(t.log_file).relative_to(output_dir)})"
            lines.append(
                f"| {i} | `{func_name}` | {status_icon} {t.status} | {t.duration}s | {report_link} | {log_link} |"
            )

        lines.append("")

    lines.append("---")
    lines.append("*Generated by OpenCode Orchestrator*")

    return "\n".join(lines)
